language: cpp
os: windows

env:
  global:
    - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"

script:
  - dir "c:\Program Files (x86)\Microsoft Visual Studio"
  - dir "c:\Program Files (x86)\Microsoft Visual Studio\2017"
  - dir "c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
  - dir "c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild"
  - export PATH=$MSBUILD_PATH:$PATH
  - MSBuild.exe TobEx.sln
